apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-ipfs.fullname" . }}
  labels:
    {{- include "go-ipfs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-ipfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "go-ipfs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-ipfs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: swarm-tcp
              containerPort: 4001
              protocol: TCP
            - name: swarm-udp
              containerPort: 4001
              protocol: UDP
            - name: daemon
              containerPort: 5001
              protocol: TCP
            - name: gateway
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "ipfs"
                - dag
                - stat
                - /ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn # empty folder
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ipfs-data
          persistentVolumeClaim:
              claimName: {{ include "go-ipfs.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
