apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "go-ipfs.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.requests.storage }}
  volumeMode: Filesystem

