apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ipfs.fullname" . }}-gateway
  labels:
    {{- include "go-ipfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: gateway
      protocol: TCP
      name: gateway
  selector:
    {{- include "go-ipfs.selectorLabels" . | nindent 4 }}
